# Rime default settings - ChillPatcher
# encoding: utf-8

config_version: '1.0.0'

# 方案列表
schema_list:
  - schema: luna_pinyin       # 明月拼音（全拼）
  - schema: double_pinyin     # 自然码双拼
  - schema: double_pinyin_abc # 智能ABC双拼
  - schema: double_pinyin_flypy # 小鹤双拼
  - schema: double_pinyin_mspy  # 微软双拼

# 菜单
menu:
  page_size: 5  # 候选词个数

# 方案选单
switcher:
  caption: 方案选单
  hotkeys:
    - F4
    - Control+grave
  save_options:
    - full_shape
    - ascii_punct
  fold_options: false
  abbreviate_options: true

# 中西文切换
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Shift_L: commit_code
    Shift_R: noop
    Control_L: noop
    Control_R: noop

# 标点符号
punctuator:
  full_shape:
    ' ' : { commit: '　' }
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ ''', ''' ] }
    '"' : { pair: [ '"', '"' ] }
    '\' : [ 、, ＼ ]
    '|' : [ ・, ｜ ]
    '`' : ｀
    '~' : ～
    '!' : { commit: ！ }
    '@' : ＠
    '#' : ＃
    '%' : ％
    '$' : [ ￥, '$', '€', '£' ]
    '^' : { commit: …… }
    '&' : ＆
    '*' : [ ＊, ·, × ]
    '(' : （
    ')' : ）
    '-' : －
    '_' : ——
    '+' : ＋
    '=' : ＝
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕, ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]
  half_shape:
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ 、, '/', ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ ''', ''' ] }
    '"' : { pair: [ '"', '"' ] }
    '\' : [ 、, '\', ＼ ]
    '|' : [ ・, '|', ｜ ]
    '`' : '`'
    '~' : '~'
    '!' : { commit: ！ }
    '@' : '@'
    '#' : '#'
    '%' : [ '%', ％ ]
    '$' : [ ￥, '$', '€', '£' ]
    '^' : { commit: …… }
    '&' : '&'
    '*' : [ '*', ＊, ·, × ]
    '(' : （
    ')' : ）
    '-' : '-'
    '_' : ——
    '+' : '+'
    '=' : '='
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕, ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]

# 按键绑定
key_binder:
  bindings:
    - { when: composing, accept: Tab, send: Page_Down }
    - { when: composing, accept: Shift+Tab, send: Page_Up }
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }

# 识别器
recognizer:
  patterns:
    email: "^[a-z][-_.0-9a-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp:|mailto:).*$"
